In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns # For visualising the data
# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/titanic/train.csv
/kaggle/input/titanic/test.csv
/kaggle/input/titanic/gender_submission.csv


### Getting an Overview of the Dataset:

- Creating dataframes to store the data:

In [2]:
df = pd.read_csv("/kaggle/input/titanic/train.csv")
test_df = pd.read_csv("/kaggle/input/titanic/test.csv")
df.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [3]:
df_testcopy = test_df.copy()

- Dropping all the unnecessary columns from the dataset:

In [4]:
df.drop(["PassengerId", "Fare", "Name", "Ticket","Cabin",],axis = 1,inplace = True)
test_df.drop(["PassengerId", "Fare", "Name", "Ticket","Cabin",],axis = 1, inplace = True)

- Checking for any null values in the dataset:

In [5]:
df.isna().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Embarked      2
dtype: int64

In [6]:
test_df.isna().sum()

Pclass       0
Sex          0
Age         86
SibSp        0
Parch        0
Embarked     0
dtype: int64

In [7]:
df.head(10)

Survived  Pclass     Sex   Age  SibSp  Parch Embarked
0         0       3    male  22.0      1      0        S
1         1       1  female  38.0      1      0        C
2         1       3  female  26.0      0      0        S
3         1       1  female  35.0      1      0        S
4         0       3    male  35.0      0      0        S
5         0       3    male   NaN      0      0        Q
6         0       1    male  54.0      0      0        S
7         0       3    male   2.0      3      1        S
8         1       3  female  27.0      0      2        S
9         1       2  female  14.0      1      0        C

In [8]:
test_df.head(10)

Pclass     Sex   Age  SibSp  Parch Embarked
0       3    male  34.5      0      0        Q
1       3  female  47.0      1      0        S
2       2    male  62.0      0      0        Q
3       3    male  27.0      0      0        S
4       3  female  22.0      1      1        S
5       3    male  14.0      0      0        S
6       3  female  30.0      0      0        Q
7       2    male  26.0      1      1        S
8       3  female  18.0      0      0        C
9       3    male  21.0      2      0        S

### Data Preprocessing:

- Importing all the necessary libraries for preprocessing:

In [9]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from scipy.stats import mode

- Taking care of the missing data:

In [10]:
# For the Training set:

df['Age'].fillna(df['Age'].mean(), inplace = True)
df["Embarked"].fillna(mode(df["Embarked"])[0][0], inplace = True)

In [11]:
# For the Test set:

test_df['Age'].fillna(test_df['Age'].mean(), inplace = True)

- Splitting the dataset into Training set and Test set:

In [12]:
X = df.iloc[:, 1:].values
y = df.iloc[:, 0].values
X_Finaltest = test_df.values
print(X)
print(y)

[[3 'male' 22.0 1 0 'S']
 [1 'female' 38.0 1 0 'C']
 [3 'female' 26.0 0 0 'S']
 ...
 [3 'female' 29.69911764705882 1 2 'S']
 [1 'male' 26.0 0 0 'C']
 [3 'male' 32.0 0 0 'Q']]
[0 1 1 1 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 1 0 1 1 1 0 1 0 0 1 0 0 1 1 0 0 0 1
 0 0 1 0 0 0 1 1 0 0 1 0 0 0 0 1 1 0 1 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0
 1 0 0 0 1 1 0 1 1 0 1 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0 1 0
 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1
 0 1 1 0 0 1 0 1 1 1 1 0 0 1 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 1 1 0 1 0 1 0
 0 0 1 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 1 0 0 0 0 0 1 1 1 0 1 1 0 1 1 0 0 0 1 0 0 0 1 0 0 1 0 1 1 1 1 0 0 0 0
 0 0 1 1 1 1 0 1 0 1 1 1 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1 1 0 1 0 1 1 1 1 0 0
 0 1 0 0 1 1 0 1 1 0 0 0 1 1 1 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 0 0 0 1 1 0 0 0 1 1 0 1 0 0 0 1 0 1 1 1 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0


- Encoding the Gender column (with Label Encoder)

In [13]:
le = LabelEncoder()
X[:, 1] = le.fit_transform(X[:, 1])
print(X)

[[3 1 22.0 1 0 'S']
 [1 0 38.0 1 0 'C']
 [3 0 26.0 0 0 'S']
 ...
 [3 0 29.69911764705882 1 2 'S']
 [1 1 26.0 0 0 'C']
 [3 1 32.0 0 0 'Q']]


In [14]:
X_Finaltest[:, 1] = le.fit_transform(X_Finaltest[:, 1])
print(X_Finaltest)

[[3 1 34.5 0 0 'Q']
 [3 0 47.0 1 0 'S']
 [2 1 62.0 0 0 'Q']
 ...
 [3 1 38.5 0 0 'S']
 [3 1 30.272590361445783 0 0 'S']
 [3 1 30.272590361445783 1 1 'C']]


- Encoding the other Categorical values (Using One Hot Encoding) [PClass and Embarked columns]

In [15]:
# For the Training set:

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0, -1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[0.0 0.0 1.0 ... 22.0 1 0]
 [1.0 0.0 0.0 ... 38.0 1 0]
 [0.0 0.0 1.0 ... 26.0 0 0]
 ...
 [0.0 0.0 1.0 ... 29.69911764705882 1 2]
 [1.0 0.0 0.0 ... 26.0 0 0]
 [0.0 0.0 1.0 ... 32.0 0 0]]


In [16]:
# For the Final test set:

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0, -1])], remainder='passthrough')
X_Finaltest = np.array(ct.fit_transform(X_Finaltest))
print(X_Finaltest)

[[0.0 0.0 1.0 ... 34.5 0 0]
 [0.0 0.0 1.0 ... 47.0 1 0]
 [0.0 1.0 0.0 ... 62.0 0 0]
 ...
 [0.0 0.0 1.0 ... 38.5 0 0]
 [0.0 0.0 1.0 ... 30.272590361445783 0 0]
 [0.0 0.0 1.0 ... 30.272590361445783 1 1]]


- Feature Scaling:

In [17]:
# For the Training set:

sc = StandardScaler()
X[:, -3: ] = sc.fit_transform(X[:, -3: ])
print(X)

[[0.0 0.0 1.0 ... -0.5924805998028886 0.43279336567850346
  -0.473673609298456]
 [1.0 0.0 0.0 ... 0.638789012042525 0.43279336567850346
  -0.473673609298456]
 [0.0 0.0 1.0 ... -0.2846631968415352 -0.4745451962498414
  -0.473673609298456]
 ...
 [0.0 0.0 1.0 ... 4.374348392294584e-15 0.43279336567850346
  2.0089333664952163]
 [1.0 0.0 0.0 ... -0.2846631968415352 -0.4745451962498414
  -0.473673609298456]
 [0.0 0.0 1.0 ... 0.17706290760049492 -0.4745451962498414
  -0.473673609298456]]


In [18]:
# For the Final Test set:

X_Finaltest[:, -3: ] = sc.transform(X_Finaltest[:, -3: ])
print(X_Finaltest)

[[0.0 0.0 1.0 ... 0.36944878445134083 -0.4745451962498414
  -0.473673609298456]
 [0.0 0.0 1.0 ... 1.3313781687055704 0.43279336567850346
  -0.473673609298456]
 [0.0 1.0 0.0 ... 2.4856934298106457 -0.4745451962498414
  -0.473673609298456]
 ...
 [0.0 0.0 1.0 ... 0.6772661874126942 -0.4745451962498414
  -0.473673609298456]
 [0.0 0.0 1.0 ... 0.04413122040295258 -0.4745451962498414
  -0.473673609298456]
 [0.0 0.0 1.0 ... 0.04413122040295258 0.43279336567850346
  0.7676298785983802]]


- Splitting the Training data into Train and Test set:

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

### Model Selection and Training:

- Importing all the necessary libraries:

In [20]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from catboost import CatBoostClassifier
from sklearn.metrics import accuracy_score, classification_report

In [21]:
lst = [("LogisticRegression",LogisticRegression(random_state = 0)),
       ("KNN Classifier", KNeighborsClassifier(n_neighbors = 5, metric='minkowski', p = 2)),
       ("Decision Tree",DecisionTreeClassifier(criterion='entropy', random_state=0)),
       ("RandomForest",RandomForestClassifier(criterion='entropy', random_state=0,n_estimators=10)),
      ("Kernel SVM",SVC(kernel='rbf', random_state= 0)),
      ("XGBoost",XGBClassifier()),
      ("Cat Boost", CatBoostClassifier())]
for name,model in lst:
    model.fit(X_train,y_train)
    y_pred = model.predict(X_test)
    acc_te = accuracy_score(y_test,y_pred)
    print(f"For {name}::\nThe Testing Accuracy is: {acc_te}")
    print("--"*40)

For LogisticRegression::
The Testing Accuracy is: 0.8044692737430168
--------------------------------------------------------------------------------
For KNN Classifier::
The Testing Accuracy is: 0.7877094972067039
--------------------------------------------------------------------------------
For Decision Tree::
The Testing Accuracy is: 0.7988826815642458
--------------------------------------------------------------------------------
For RandomForest::
The Testing Accuracy is: 0.7988826815642458
--------------------------------------------------------------------------------
For Kernel SVM::
The Testing Accuracy is: 0.8156424581005587
--------------------------------------------------------------------------------
For XGBoost::
The Testing Accuracy is: 0.8324022346368715
--------------------------------------------------------------------------------
Learning rate set to 0.008911
0:	learn: 0.6871180	total: 57.9ms	remaining: 57.9s
1:	learn: 0.6821252	total: 59.3ms	remaining: 29.6s
2:

### Optimising the model by hyperparameter tuning:

- Applying Grid Search for Kernel SVM:

In [22]:
from sklearn.model_selection import GridSearchCV
classifier = SVC(kernel='rbf', random_state= 0)
parameters = [{'C': [0.25, 0.5, 0.75, 1.0], 'kernel': ['linear']}, {'C': [0.25, 0.5, 0.75, 1.0], 'kernel': ['rbf'], 'gamma': [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]}]
grid_search =GridSearchCV(estimator = classifier, param_grid = parameters, scoring = 'accuracy', cv = 10, n_jobs = -1)
grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
print("Best Parameters : ",  best_parameters)

Best Accuracy: 83.02 %
Best Parameters :  {'C': 0.75, 'gamma': 0.2, 'kernel': 'rbf'}


- Applying Grid Search on Logistic Regression:

In [23]:
parameters = [{'C' : np.logspace(-3,3,7), 'max_iter' : [100, 200, 500, 1000], 'solver' : ['liblinear']}]
classifier = LogisticRegression()
grid_search =GridSearchCV(estimator = classifier, param_grid = parameters, scoring = 'accuracy', cv = 10, n_jobs = -1)
grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
print("Best Parameters : ",  best_parameters)

Best Accuracy: 80.90 %
Best Parameters :  {'C': 0.1, 'max_iter': 100, 'solver': 'liblinear'}


- Applying Grid Search on XGBoost:

In [24]:
parameters = {'max_depth': range (2, 10, 1), 'n_estimators': range(60, 220, 40), 'learning_rate': [0.1, 0.01, 0.05]}
classifier = XGBClassifier()
grid_search = GridSearchCV(estimator = classifier, param_grid=parameters, scoring = 'roc_auc', n_jobs = -1, cv = 10, verbose=True)
grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
print("Best Parameters : ",  best_parameters)

Fitting 10 folds for each of 96 candidates, totalling 960 fits
Best Accuracy: 87.27 %
Best Parameters :  {'learning_rate': 0.01, 'max_depth': 5, 'n_estimators': 140}


- Creating a model with Voting Classifier:

In [25]:
from sklearn.ensemble import VotingClassifier
estimator = []
estimator.append(("LogisticRegression",LogisticRegression(random_state = 0, C = 0.1, max_iter = 100, solver = 'liblinear')))
estimator.append(("Kernel SVM",SVC(kernel='rbf', random_state= 0, gamma = 0.2, C = 0.75, probability = True)))
estimator.append(("XGBoost",XGBClassifier(learning_rate = 0.01, max_depth = 5, n_estimators = 140)))
estimator.append(("Cat Boost", CatBoostClassifier()))
vot_soft = VotingClassifier(estimators = estimator, voting ='soft')
vot_soft.fit(X_train, y_train)
y_pred = vot_soft.predict(X_test)

Learning rate set to 0.008911
0:	learn: 0.6871180	total: 1.76ms	remaining: 1.76s
1:	learn: 0.6821252	total: 2.95ms	remaining: 1.47s
2:	learn: 0.6770686	total: 4.44ms	remaining: 1.48s
3:	learn: 0.6719674	total: 5.6ms	remaining: 1.39s
4:	learn: 0.6668388	total: 6.83ms	remaining: 1.36s
5:	learn: 0.6620883	total: 8.09ms	remaining: 1.34s
6:	learn: 0.6568873	total: 9.32ms	remaining: 1.32s
7:	learn: 0.6526174	total: 10.5ms	remaining: 1.3s
8:	learn: 0.6475025	total: 11.7ms	remaining: 1.29s
9:	learn: 0.6433704	total: 12.5ms	remaining: 1.24s
10:	learn: 0.6386167	total: 13.6ms	remaining: 1.22s
11:	learn: 0.6350648	total: 14.8ms	remaining: 1.22s
12:	learn: 0.6304173	total: 16.1ms	remaining: 1.22s
13:	learn: 0.6257774	total: 17.3ms	remaining: 1.22s
14:	learn: 0.6218534	total: 18.4ms	remaining: 1.21s
15:	learn: 0.6177850	total: 19.6ms	remaining: 1.2s
16:	learn: 0.6146282	total: 20.6ms	remaining: 1.19s
17:	learn: 0.6104209	total: 21.8ms	remaining: 1.19s
18:	learn: 0.6067072	total: 22.7ms	remaining: 1

In [26]:
score = accuracy_score(y_test, y_pred)
print(score*100, ' %')

82.68156424581005  %


### Exporting the Prediction:

In [27]:
final_prediction = vot_soft.predict(X_Finaltest)
final_df = pd.DataFrame({"PassengerId": df_testcopy["PassengerId"],"Survived": final_prediction})
final_df.to_csv("submission_2.csv",index = False)
final_df.head(10)

PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         1
5          897         0
6          898         1
7          899         0
8          900         1
9          901         0